name: expense_repository
description: "A Repo thet handels expenses"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
